### ISSUE TITLE
Training on pedestrian and cyclist

### ISSUE THREAD

**Issue by Nourhan27** [tomztyang/3DSSD#33]
Hello,

First, Thanks for this great work.  My question is how to train the model on pedestrian and cyclist, because i want to match the results reported by the paper for the three classes (car, pedestrian, cyclist)

**Comment by zye1996** [comment]
> Hello,
> 
> First, Thanks for this great work. My question is how to train the model on pedestrian and cyclist, because i want to match the results reported by the paper for the three classes (car, pedestrian, cyclist)

I am also looking into this and I am pretty sure you can achieve this by modifying the config file to change the class_name and the corresponding evaluation method. And I have done this on 3dssd using mmdetection3d framework if you want to have a look at that implementation

**Comment by Nourhan27** [comment]
Hello @zye1996 , 
Thanks for your reply. Could you provide me with the link for the modification done in 3dssd using mmdetection3d framework.
Thanks,

**Comment by zye1996** [comment]
> Hello,
> 
> First, Thanks for this great work. My question is how to train the model on pedestrian and cyclist, because i want to match the results reported by the paper for the three classes (car, pedestrian, cyclist)

I implemented the Pytorch version predicting all three classes [here](https://github.com/zye1996/3DSSD-torch) if you are still interested

**Comment by RolandoAvides** [comment]
Hello @zye1996, could give any suggestion on how to configure the script in order to train in 3 classes?

Additionally, do you think it is better to train on cars and train on ped&cyc, or train in all 3 classes?

 I'm currently using 3DSSD from Open-PCDet and changed the class_names and num_classes. However, I still can't evaluate pedestrians and cyclists.
 
 Thanks in advance!

**Comment by wangy12** [comment]
> > Hello,
> > First, Thanks for this great work. My question is how to train the model on pedestrian and cyclist, because i want to match the results reported by the paper for the three classes (car, pedestrian, cyclist)
> 
> I implemented the Pytorch version predicting all three classes [here](https://github.com/zye1996/3DSSD-torch) if you are still interested

Hi @zye1996 , Will you please share how you changed the config and evaluation of 3DSSD to support multi-class? I looked at your repo of mmdetection3d but no luck. Thanks in advance!!

**Comment by zye1996** [comment]
> > > Hello,
> > > First, Thanks for this great work. My question is how to train the model on pedestrian and cyclist, because i want to match the results reported by the paper for the three classes (car, pedestrian, cyclist)
> > 
> > 
> > I implemented the Pytorch version predicting all three classes [here](https://github.com/zye1996/3DSSD-torch) if you are still interested
> 
> Hi @zye1996 , Will you please share how you changed the config and evaluation of 3DSSD to support multi-class? I looked at your repo of mmdetection3d but no luck. Thanks in advance!!

Please reach me through zhenyiye1996@gmail.com and I will add you to the repo
